import { Metadata } from 'next';
import React from 'react';
import Footer from '../components/Footer/Footer';
import Instructional from '../components/Instructional/Instructional';
import MenuItems from '../components/NavBar/MenuItems/MenuItems';
import "../globals.css";
import { Providers } from '../providers';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function HomeLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`bg-white dark:bg-medium font-outfit`}>
                <Providers>
                    <div className=" relative ">
                        <div className='absolute inset-0 -z-30 dark:brightness-50 bg-center bg-cover bg-no-repeat' style={{ backgroundImage: "url('/images/moneyTransferHomeBg.JPG')" }}></div>
                        <div className='container mx-auto px-2 sm:px-4 lg:px-10 2lg:px-20'>
                            <MenuItems></MenuItems>
                        </div>
                        <div className='min-h-[100vh] flex items-center justify-center mt-10 2lg:-mt-[56px]'>
                            <div className='container mx-auto px-2 sm:px-4 lg:px-10 2lg:px-20 flex justify-center items-center '>
                                {children}
                            </div>

                        </div>
                    </div>
                    <div className='container mx-auto px-2 sm:px-4 lg:px-10 2lg:px-20'>
                        <Instructional></Instructional>
                    </div>
                    <Footer></Footer>
                </Providers>

            </body>
        </html>
    )
}

export default HomeLayout
